version: '3.2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: kseasy

  keycloak-authenticator:
    container_name: kseasy-keycloak
    build: .
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: kseasy
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: kseasy
      JDBC_PARAMS: "useSSL=false"
    expose:
      - '8080'
    ports:
      - '9990:8080'
    depends_on:
      - mysql

volumes:
  mysql_data_volume:
    driver: local